services:
#    awaresoft.user.change_password.form.type:
#        class: Awaresoft\Sonata\UserBundle\Form\Type\ChangePasswordFormType
#        tags:
#            - { name: form.type, alias: awaresoft_user_change_password_form }
#        arguments:
#            - "%fos_user.model.user.class%"
#
#    awaresoft.user.change_password.form.factory:
#        class: Awaresoft\Sonata\UserBundle\Form\Factory\FormFactory
#        arguments:
#            - "@form.factory"
#            - "%fos_user.change_password.form.name%"
#            - "%fos_user.change_password.form.type%"
#            - "%fos_user.change_password.form.validation_groups%"