services:
    awaresoft.user.listener.login_failure_handler:
        parent: security.authentication.failure_handler
        class:  Awaresoft\Sonata\UserBundle\EventListener\LoginFailureHandler
        calls:
            - [ setContainer, [@service_container]]