parameters:
    sonata.user.orm.user_manager.class: Awaresoft\Sonata\UserBundle\Manager\UserManager

services:
    sonata.user.orm.user_manager:
        class: "%sonata.user.orm.user_manager.class%"
        arguments:
            - "@fos_user.util.password_updater"
            - "@fos_user.util.canonical_fields_updater"
            - "@fos_user.object_manager"
            - "%fos_user.model.user.class%"
        calls:
            - [setContainer, ["@service_container"]]